language: ruby
rvm:
- 2.3.3

install: gem install jekyll
script: jekyll build

sudo: false
exclude: [vendor]

deploy:
  provider: pages
  skip_cleanup: true
  local-dir: ./site
  api_key:
    secure: "rhOnOJ+Zn9tXItq0WDgmKtB13wGY4XZtjEOwlaZRrhkH3VzC8eh2Nc9OkK8YXswAKi5kLdkaEG94AHPBg8soH6JLLnzXeXRU1DtZJpDr+aBfGaYkSNbaCj8Drc4a+lHRQ2utCjjTI84vgvJZZx7keDWK+/eZD6kP5fcYWm0/BYqneuCKh56ch9ZBPY42J13XlxjOXjFUDnVCaRTyBu2tVNhm4iqZ3JkJamxvpf1+7VWInRoZa2U0vj/C6pg7qa9sT6EYqEA8C2TklHQ4VK/+tTXMaPSDc/8tYyWCE6EU3ujOWvxT4FSQKg3SMgg3z0OYSLoYKSIkY9b6n/AY5F/IcF8DkcnMNinRY5TfgyF13Skso+rZBXT4niIfnhN4DWsLKlehykWqk37lm+dCCyHb3RCVv2Ors70B6YiSCohs8mp+E/njWpViyWOkmS2nV+yacbgTKF4nenyCGJjuCU+d9KHOExmvV1VfnF/6p2tL9oxKvNRv7XWSSwIXXfT/akfy+3lF9QDwK7IXy9s9FouWTHIIsVh2whWIIcZtslz4iCsDr5NLHZVLQWT12zYKRW0QkOUKYzKan04HYnowLWpAA9TE01Zko+7OJuiHKH7eezbcdBkW8lEDsqGhBes26b/+jsASt5hRYE3KQssQRqaX3slEdgAvJmQvOjlS/Tipf2I="
  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master


cat $DEPLOY_KEY > .travis/deploy_key.pem
