language: ruby
cache: bundler
rvm:
- 2.3.3

branches:
  only:
  - release

install: gem install jekyll
script:
  - bundle exec jekyll build

sudo: false
exclude: [vendor]

deploy:
  provider: pages
  local-dir: ./_site
  target-branch: master
  skip_cleanup: true
  github-token: $GITHUB_TOKEN
  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: release
